name: speech_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - sympy=1.13.1
  - ffmpeg
  - sox
  - pip
  - pip:
    - transformers
    - psutil
    - gputil
    - tokenizers
    - huggingface-hub 